### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by withrvr** [tusharnankani/undirected-graph#10]
## Website not responsive

- works fine in mobile and desktop view only
- not in other views / gadgets
 - tablet.... etc

## Ref Image

- ![image](https://user-images.githubusercontent.com/69628500/151198907-ac2ede6c-6618-4443-9cac-0c2064216872.png)
- ![image](https://user-images.githubusercontent.com/69628500/151198995-b60d78cd-4937-4379-9e1c-af7b032bea75.png)

## may be change in this will work
- z index
- padding
- margin

**Comment by tusharnankani** [comment]
Hey
Thanks for pointing this out! Will fix it in the next deployment 🚀

**Comment by tusharnankani** [comment]
@withrvr I have tried to fix this.
Can you try it out and let me know?

**Comment by tusharnankani** [comment]
Fixed other screens 👍🏻
